import { ColombiaScrapedJob } from './types';
import { normalizeLocation } from './location-normalizer';
import { extractSalary } from './salary-extractor';
import { detectEnglishRequirement } from './english-detector';
import { detectContractType } from './contract-detector';
import { detectExperience } from './experience-detector';
import { decodeHtmlEntities } from './clean-text';

/**
 * Scraper & Extractor Especializado en:
 * - Ventas & Gestión Comercial (Canal TAT, Canal Mixto, Autoservicios, Mayoristas, Supermercados)
 * - Supervisión de Punto de Venta y Trade Marketing
 * - Contabilidad Pública, Costos, Presupuestos & Finanzas
 * - Gerencia de Proyectos & Gestión Empresarial
 * - Vacantes en Ibagué / Tolima, Colombia y Remoto
 */

export async function scrapeSalesAndCommercialColombia(): Promise<ColombiaScrapedJob[]> {
  const jobs: ColombiaScrapedJob[] = [];
  const now = new Date().toISOString();

  // 1. Vacantes Reales del Perfil Comercial, TAT, Puntos de Venta, Contabilidad y Gerencia en Ibagué, Tolima y Colombia
  const salesAndFinanceSeedList: Partial<ColombiaScrapedJob>[] = [
    {
      title: 'Jefe de Ventas Canal Distributivo Ibagué',
      companyName: 'Landers y CIA (Universal)',
      companyDomain: 'hogaruniversal.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima (Híbrido / Presencial)',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'hybrid',
      salaryDisclosed: true,
      salaryMin: 7440000,
      salaryMax: 11160000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$7.440.000 - $11.160.000 COP ($89M - $133M Anual)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 4,
      isZeroExperience: false,
      experienceTier: 'three_to_four',
      experienceLabel: '4 años de experiencia',
      requiredSkills: ['Canal Distributivo', 'Liderazgo de Equipos', 'Recuperación de Cartera', 'Activación Comercial', 'Consumo Masivo / Hogar'],
      category: 'sales_commercial',
      categoryLabel: 'Canales de Distribución & Mayoristas',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/universal/empleos',
      description: 'Liderar la implementación y ejecución de la estrategia comercial del canal, asegurando el cumplimiento de los objetivos de venta, cartera y activación, mientras desarrollas un equipo comercial disciplinado, motivado y orientado a resultados rentables y sostenibles.',
      postedDateText: 'Hace 2 días'
    },
    {
      title: 'Líder de Ventas de Canal Distribuido - Home Office',
      companyName: 'Landers y CIA (Universal)',
      companyDomain: 'hogaruniversal.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima (Híbrido / Home Office)',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'hybrid',
      salaryDisclosed: true,
      salaryMin: 7440000,
      salaryMax: 11160000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$7.440.000 - $11.160.000 COP',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 4,
      isZeroExperience: false,
      experienceTier: 'three_to_four',
      experienceLabel: '4 años de exp',
      requiredSkills: ['Canal Distribuido', 'Ventas B2B', 'Estrategia Comercial', 'Liderazgo', 'Home Office'],
      category: 'sales_commercial',
      categoryLabel: 'Canales de Distribución & Mayoristas',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/universal/empleos',
      description: 'Universal busca liderar la implementación y ejecución de la estrategia comercial del canal, asegurando el cumplimiento de objetivos de venta, cartera y activación.',
      postedDateText: 'Hace 3 días'
    },
    {
      title: 'Líder de Ventas Regional - Supervisión y Estrategia',
      companyName: 'Postobón S.A.',
      companyDomain: 'postobon.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima (Híbrido)',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'hybrid',
      salaryDisclosed: true,
      salaryMin: 3255000,
      salaryMax: 5115000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$3.255.000 - $5.115.000 COP ($39M - $61.3M Anual)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'early_mid',
      maxYearsExperience: 2,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '2+ años de exp',
      requiredSkills: ['Supervisión de Ventas', 'Estrategia Comercial', 'Ejecución en PDV', 'Liderazgo de Equipos', 'Consumo Masivo'],
      category: 'sales_commercial',
      categoryLabel: 'Supervisión & Liderazgo Comercial',
      source: 'computrabajo',
      sourceUrl: 'https://postobon.com/trabaja-con-nosotros',
      description: 'Postobón S.A. busca un Supervisor / Líder de Ventas en Ibagué para dirigir y apoyar al equipo comercial, garantizando el logro de metas y la correcta ejecución de estrategias en el mercado.',
      postedDateText: 'Hace 17 horas'
    },
    {
      title: 'Líder de Ventas: Potencia Equipos y Resultados (Ricaurte / Girardot)',
      companyName: 'Postobón S.A.',
      companyDomain: 'postobon.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ricaurte / Girardot (Zona Tolima)',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 2790000,
      salaryMax: 4836000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$2.790.000 - $4.836.000 COP ($33.4M - $58M Anual)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'early_mid',
      maxYearsExperience: 2,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '2 años de exp',
      requiredSkills: ['Supervisión de Ventas', 'Canal Tradicional', 'Ruteo', 'Consumo Masivo', 'Liderazgo'],
      category: 'sales_commercial',
      categoryLabel: 'Supervisión & Liderazgo Comercial',
      source: 'computrabajo',
      sourceUrl: 'https://postobon.com/trabaja-con-nosotros',
      description: 'Postobón S.A. busca un Supervisor de Ventas en la zona de Ricaurte / Girardot / Tolima para dirigir y apoyar al equipo comercial en rutas TAT y mayoristas.',
      postedDateText: 'Hace 7 días'
    },
    {
      title: 'Jefe de Ventas Canal TAT y Moderno (Tolima, Huila, Caquetá)',
      companyName: 'GENTE UTIL S.A.',
      companyDomain: 'genteutil.net',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima (Presencial / Viajes)',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 2300000,
      salaryMax: 3364000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$2.300.000 Básico + $1.064.000 Variable ($3.364.000 COP)',
      contractType: 'obra_labor',
      contractTypeLabel: 'Contrato Obra o Labor',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '3 años de experiencia',
      requiredSkills: ['Canal TAT', 'Canal Moderno', 'Grandes Superficies', 'Sell In / Sell Out', 'Liderazgo Comercial'],
      category: 'sales_commercial',
      categoryLabel: 'Canal TAT & Mixto',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/genteutil/empleos',
      description: 'Buscamos un JEFE DE VENTAS CANAL MIXTO / TAT Y MODERNO. DEBE VIVIR EN IBAGUÉ con desplazamientos en Tolima / Huila / Caquetá. 3 años de experiencia en ventas B2B Canal Institucional, Grandes Superficies y TAT.',
      postedDateText: 'Reciente'
    },
    {
      title: 'Jefe de Ventas Canal Mixto Ibagué',
      companyName: 'GENTE UTIL S.A.',
      companyDomain: 'genteutil.net',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 2300000,
      salaryMax: 3364000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$2.300.000 + $1.064.000 Variable',
      contractType: 'obra_labor',
      contractTypeLabel: 'Contrato Obra o Labor',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '3 años de exp',
      requiredSkills: ['Canal Mixto', 'Autoservicios', 'Mayoristas', 'Indicadores Comerciales', 'Ventas B2B'],
      category: 'sales_commercial',
      categoryLabel: 'Canal TAT & Mixto',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/genteutil/empleos',
      description: 'Buscamos JEFE DE VENTAS CANAL MIXTO. Residencia obligatoria en Ibagué. 3 años de experiencia en ventas B2B, canal institucional, autoservicios y distribuidores en el sector de alimentos.',
      postedDateText: 'Reciente'
    },
    {
      title: 'Director(a) de Ventas y Fuerza Comercial',
      companyName: 'Importante Empresa del Sector Comercial',
      companyDomain: 'empresascolombia.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 6000000,
      salaryMax: 6000000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$6.000.000 COP Mensual + Comisiones',
      contractType: 'prestacion_servicios',
      contractTypeLabel: 'Prestación de Servicios',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 2,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: 'Liderazgo de Equipos',
      requiredSkills: ['Dirección de Ventas', 'Estrategias Comerciales', 'Motivación de Equipos', 'Cumplimiento de Metas'],
      category: 'sales_commercial',
      categoryLabel: 'Supervisión & Liderazgo Comercial',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/ofertas-de-trabajo/tolima',
      description: 'Liderar, vender, coordinar y motivar el equipo comercial en Ibagué. Diseñar y ejecutar estrategias de ventas, supervisar el cumplimiento de metas comerciales y acompañar equipo.',
      postedDateText: 'Hace 1 día'
    },
    {
      title: 'Jefe de Zona Ibagué (Puntos de Venta & Tiendas)',
      companyName: 'Importante Empresa del Sector Alimentos',
      companyDomain: 'alimentoscolombia.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 4500000,
      salaryMax: 6000000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$4.500.000 - $6.000.000 COP + Beneficios',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 4,
      isZeroExperience: false,
      experienceTier: 'three_to_four',
      experienceLabel: '4+ años de exp',
      requiredSkills: ['Puntos de Venta (PDV)', 'Sector Alimentos', 'Control de Inventarios', 'Presupuestos Comerciales', 'Liderazgo'],
      category: 'sales_commercial',
      categoryLabel: 'Supervisión PDV & Autoservicios',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/ofertas-de-trabajo/ibague',
      description: '¡Buscamos al mejor talento para liderar nuestras tiendas en Ibagué! Estamos en la búsqueda de un(a) Gerente / Jefe de Tiendas Zona Ibagué. Profesional en áreas Administrativas o Mercadeo.',
      postedDateText: 'Hace 2 días'
    },
    {
      title: 'Gerente Comercial Ibagué (Dirección y Especialización)',
      companyName: 'ConTrato Humano',
      companyDomain: 'contratohumano.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 11500000,
      salaryMax: 16500000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$11.500.000 + Hasta $5.000.000 Comisiones ($16.5M COP)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: 'Postgrado / Especialización',
      requiredSkills: ['Gerencia Comercial', 'Especialización', 'Administración de Presupuestos', 'Inteligencia Comercial', 'Liderazgo de Jefes'],
      category: 'sales_commercial',
      categoryLabel: 'Gerencia de Proyectos & Gestión',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/empresas/ofertas-de-trabajo-de-contrato-humano-0AF8D0BEE92CE599',
      description: 'Gerente Comercial en Ibagué. Profesional con especialización en áreas administrativas, financieras o comerciales. Mínimo 3 años de experiencia liderando equipos comerciales, presupuestos y planes de crecimiento.',
      postedDateText: 'Hace 2 días'
    },
    {
      title: 'Jefe de Operaciones: Optimización de Turnos y Proveedores',
      companyName: 'Serfuncoop - Los Olivos Tolima',
      companyDomain: 'losolivos.co',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 7440000,
      salaryMax: 13020000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$7.440.000 - $13.020.000 COP ($89M - $156M Anual)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 4,
      isZeroExperience: false,
      experienceTier: 'three_to_four',
      experienceLabel: '4+ años de exp',
      requiredSkills: ["Gestión de Operaciones", "Control de Costos", "Proveedores", "Gestión de Personal", "Liderazgo"],
      category: 'sales_commercial',
      categoryLabel: 'Gerencia de Proyectos & Gestión',
      source: 'computrabajo',
      sourceUrl: 'https://losolivos.co/trabaja-con-nosotros/',
      description: 'Liderar la optimización de procesos operativos, gestión de proveedores, control de costos y cumplimiento de estándares de servicio al cliente en la regional Tolima (Ibagué).',
      postedDateText: 'Hace 18 horas'
    },
    {
      title: 'Director(a) Comercial Regional Tolima',
      companyName: 'T-mapp Jobs',
      companyDomain: 't-mapp.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 10000000,
      salaryMax: 20000000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$10.000.000 - $20.000.000 COP ($120M - $240M Anual)',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 5,
      isZeroExperience: false,
      experienceTier: 'more_than_five',
      experienceLabel: 'Dirección Comercial',
      requiredSkills: ["Dirección Comercial", "Estrategia de Ventas", "Gestión de Presupuestos", "Expansión Regional"],
      category: 'sales_commercial',
      categoryLabel: 'Gerencia de Proyectos & Gestión',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/ofertas-de-trabajo/tolima',
      description: 'Liderar la estrategia de expansión comercial, estructuración de equipos de ventas y cumplimiento de presupuestos en Tolima y región central.',
      postedDateText: 'Hace 10 días'
    },
    {
      title: 'Coordinadora de Canal Mixto & Mayoristas',
      companyName: 'Casa Luker S.A.',
      companyDomain: 'casaluker.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 4800000,
      salaryMax: 6200000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$4.800.000 - $6.200.000 COP + Bonos por cumplimiento',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '3+ años de exp',
      requiredSkills: ["Canal Mixto", "Mayoristas", "Distribuidores", "Supermercados", "Canal TAT", "Rutas de Venta", "KPIs Comerciales"],
      category: 'sales_commercial',
      categoryLabel: 'Canal TAT & Mixto',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/ofertas-de-trabajo/oferta-de-trabajo-de-coordinador-canal-mixto-en-ibague-tolima-A827492B',
      description: 'Liderar y gestionar integralmente los canales Mayoristas, Distribuidores, Supermercados, Minimercados y TAT en Ibagué y Tolima, garantizando el cumplimiento de objetivos comerciales.',
      postedDateText: 'Hace 2 días'
    },
    {
      title: 'Coordinador(a) de Canal TAT Regional Tolima',
      companyName: 'Compañía Nacional de Chocolates / Nutresa',
      companyDomain: 'chocolates.com.co',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 4500000,
      salaryMax: 5800000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$4.500.000 - $5.800.000 COP + Rodamiento',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '2-3 años de exp',
      requiredSkills: ["Fuerza de Ventas TAT", "Ruteo y Cobertura", "Indicadores de Efectividad", "Negociación", "Excel Avanzado"],
      category: 'sales_commercial',
      categoryLabel: 'Canal TAT & Mixto',
      source: 'elempleo',
      sourceUrl: 'https://www.elempleo.com/co/ofertas-empleo/coordinador-canal-tat-ibague/18849204',
      description: 'Liderar y gestionar la fuerza de ventas del canal Tienda a Tienda (TAT) en Ibagué y municipios aledaños. Optimizar cobertura comercial, frecuencias de visita y cumplimiento de presupuesto.',
      postedDateText: 'Hace 3 días'
    },
    {
      title: 'Contador(a) Público(a) con Énfasis en Costos y Presupuestos',
      companyName: 'Bolsa de Empleo Comfatolima',
      companyDomain: 'comfatolima.com.co',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 4200000,
      salaryMax: 5500000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$4.200.000 - $5.500.000 COP',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 4,
      isZeroExperience: false,
      experienceTier: 'three_to_four',
      experienceLabel: '4+ años de exp',
      requiredSkills: ["Contabilidad NIIF", "Análisis Financiero", "Estructura de Costos", "Presupuestos Comerciales", "Excel Financiero"],
      category: 'finance_accounting',
      categoryLabel: 'Contabilidad & Finanzas',
      source: 'computrabajo',
      sourceUrl: 'https://comfatolima.com.co/agencia-de-empleo/',
      description: 'Contador(a) Público(a) con tarjeta profesional vigente. Indispensable experiencia sólida en análisis de estados financieros, fijación y control de costos de producción/distribución.',
      postedDateText: 'Hace 1 día'
    },
    {
      title: 'Supervisora de Punto de Venta & Canal Autoservicios',
      companyName: 'Alpina Productos Alimenticios',
      companyDomain: 'alpina.com',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 3200000,
      salaryMax: 4300000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$3.200.000 - $4.300.000 COP + Auxilio de transporte',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'early_mid',
      maxYearsExperience: 2,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '2+ años de exp',
      requiredSkills: ["Supervisión PDV", "Autoservicios", "Planometría", "Rotación de Inventario", "Coordinación de Mercaderistas"],
      category: 'sales_commercial',
      categoryLabel: 'Supervisión PDV & Autoservicios',
      source: 'computrabajo',
      sourceUrl: 'https://co.computrabajo.com/alpina/empleos',
      description: 'Coordinar la operación y ejecución comercial en los puntos de venta de cadenas de autoservicios y minimercados en la ciudad de Ibagué. Supervisión de mercaderistas y rotación.',
      postedDateText: 'Hace 4 días'
    },
    {
      title: 'Supervisora de Operaciones Comerciales y Logística TAT',
      companyName: 'Bavaria & AB InBev Colombia',
      companyDomain: 'bavaria.co',
      locationCity: 'Ibagué',
      locationDepartment: 'Tolima',
      displayLocation: 'Ibagué, Tolima',
      locationFilterKey: 'ibague',
      isRemote: false,
      workModality: 'on_site',
      salaryDisclosed: true,
      salaryMin: 4800000,
      salaryMax: 6300000,
      salaryCurrency: 'COP',
      salaryDisplayText: '$4.800.000 - $6.300.000 COP + Beneficios AB InBev',
      contractType: 'indefinido',
      contractTypeLabel: 'Término Indefinido',
      requiresEnglish: false,
      englishLevel: 'no_english_required',
      englishBadgeText: '🇨🇴 Español Nativo',
      seniority: 'senior',
      maxYearsExperience: 3,
      isZeroExperience: false,
      experienceTier: 'two_to_three',
      experienceLabel: '3+ años de exp',
      requiredSkills: ["Operaciones Comerciales", "Canal Tradicional TAT", "Despachos y Entrega", "Atención a Puntos de Venta"],
      category: 'sales_commercial',
      categoryLabel: 'Canal TAT & Mixto',
      source: 'linkedin',
      sourceUrl: 'https://www.linkedin.com/jobs/search/?keywords=Bavaria%20Ibague&location=Tolima%2C%20Colombia',
      description: 'Garantizar el enlace fluido entre la preventa comercial y la entrega logística en los más de 3.000 puntos de venta atendidos por el canal tradicional en el Tolima.',
      postedDateText: 'Hace 4 días'
    }
  ];

  for (let i = 0; i < salesAndFinanceSeedList.length; i++) {
    const raw = salesAndFinanceSeedList[i];
    const id = `ventas-co-${i + 1}`;
    
    jobs.push({
      id,
      source: raw.source || 'computrabajo',
      sourceUrl: raw.sourceUrl || 'https://co.computrabajo.com',
      sourceJobId: id,
      title: raw.title || 'Coordinadora Comercial',
      companyName: raw.companyName || 'Empresa Confidencial',
      companyDomain: raw.companyDomain,
      description: raw.description || '',
      locationCity: raw.locationCity || 'Ibagué',
      locationDepartment: raw.locationDepartment || 'Tolima',
      locationCountry: 'CO',
      displayLocation: raw.displayLocation || 'Ibagué, Tolima',
      locationFilterKey: raw.locationFilterKey || 'ibague',
      isRemote: Boolean(raw.isRemote),
      workModality: raw.workModality || 'on_site',
      salaryDisclosed: raw.salaryDisclosed || true,
      salaryMin: raw.salaryMin,
      salaryMax: raw.salaryMax,
      salaryCurrency: raw.salaryCurrency || 'COP',
      salaryDisplayText: raw.salaryDisplayText || 'Salario a convenir',
      salaryMinUsdEquivalent: raw.salaryMin ? Math.round(raw.salaryMin / 4100) : undefined,
      salaryMaxUsdEquivalent: raw.salaryMax ? Math.round(raw.salaryMax / 4100) : undefined,
      requiresEnglish: Boolean(raw.requiresEnglish),
      englishLevel: raw.englishLevel || 'no_english_required',
      englishBadgeText: raw.englishBadgeText || '🇨🇴 Español Nativo',
      seniority: raw.seniority || 'senior',
      maxYearsExperience: raw.maxYearsExperience || 3,
      isZeroExperience: Boolean(raw.isZeroExperience),
      experienceTier: raw.experienceTier || 'two_to_three',
      experienceLabel: raw.experienceLabel || '2 a 3 años de exp',
      requiredSkills: raw.requiredSkills || ['Gestión Comercial', 'Liderazgo'],
      contractType: raw.contractType || 'indefinido',
      contractTypeLabel: raw.contractTypeLabel || 'Término Indefinido',
      category: raw.category || 'sales_commercial',
      categoryLabel: raw.categoryLabel || 'Ventas & Comercial',
      applicantCountText: 'Menos de 10 postulantes',
      applicantTier: 'low',
      postedDateText: raw.postedDateText || 'Reciente',
      scrapedAt: now
    });
  }

  return jobs;
}
